# Netlify configuration file

[build]
  command = "npm run build" # Command to build your Next.js site
  publish = ".next"         # Directory that contains the built assets for Next.js (includes static and serverless functions)

# Explicitly use the Next.js runtime plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev" # Command to run your site locally
  port = 9002 # Port for local development server
  publish = ".next" # Should match your build.publish if you want `netlify dev` to mimic production closely
  # framework = "#static" # Uncomment if you were doing a pure static export to `out`
  # targetPort = 3000 # If your dev server runs on a different port internally