backend:
  name: git-gateway
  branch: master # or 'master' — match your repo's default
  identity_url: https://nocturnal-codex.netlify.app/.netlify/identity
  gateway_url: https://nocturnal-codex.netlify.app/.netlify/git
  role: editor

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "The Nocturnist" }
      - { label: "Tags", name: "tags", widget: "list", default: ["New Post"] }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Featured Image", name: "imageUrl", widget: "image", required: false }
      - { label: "Image AI Hint", name: "dataAiHint", widget: "string", required: false, hint: "Keywords for AI image search if placeholder, e.g., 'abstract technology'" }
      - { label: "Series ID", name: "seriesId", widget: "string", required: false, hint: "e.g., 'quantum-intro'. Must match an ID in lib/data.ts (for now)"}
      - { label: "Series Order", name: "seriesOrder", widget: "number", value_type: "int", required: false, hint: "e.g., 1, 2, 3..."}
      - { label: "Body", name: "body", widget: "markdown" }

    editor:
      preview: true
