backend:
  name: git-gateway # Use Netlify's Git Gateway for authentication and GitHub interaction
  branch: master # Or 'main', or your default branch

media_folder: "public/images/blog" # Location where new media files will be saved
public_folder: "/images/blog" # The src attribute for uploaded media will begin with this path

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the CMS UI
    folder: "content/blog" # The path to the folder where blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" } # Optional: for other SSGs
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "The Nocturnist" } # Default author
      - { label: "Tags", name: "tags", widget: "list", default: ["New Post"] }
      - { label: "Excerpt", name: "excerpt", widget: "text" } # Short summary
      - { label: "Featured Image", name: "imageUrl", widget: "image", required: false }
      - { label: "Image AI Hint", name: "dataAiHint", widget: "string", required: false, hint: "Keywords for AI image search if placeholder, e.g., 'abstract technology'" }
      - { label: "Series ID", name: "seriesId", widget: "string", required: false, hint: "e.g., 'quantum-intro'. Must match an ID in lib/data.ts (for now)"}
      - { label: "Series Order", name: "seriesOrder", widget: "number", value_type: "int", required: false, hint: "e.g., 1, 2, 3..."}
      - { label: "Body", name: "body", widget: "markdown" }
    editor: # Editor settings (optional)
      preview: true
