backend:
  name: github # Refer to https://decapcms.org/docs/backends-overview/
  repo: your-username/your-repo-name # e.g. NocturnalCodex/nocturnal-codex-app
  branch: main # Branch to update (optional; defaults to master)
  # For local development with GitHub OAuth, you might not need client_id if using implicit grant
  # For production, especially with Netlify Git Gateway, this might change or use Netlify Identity
  # client_id: YOUR_GITHUB_OAUTH_CLIENT_ID # Optional, for GitHub API rate limiting
  # base_url: https://your-site.com # Optional, for OAuth redirects and media URLs
  # auth_endpoint: auth # Optional, for custom OAuth handling

media_folder: "public/images/blog" # Location where files will be stored in the repo
public_folder: "/images/blog" # The src attribute for uploaded media

publish_mode: editorial_workflow # Optional: Enables a custom workflow for drafting, reviewing, and publishing.

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the Decap CMS UI
    folder: "content/blog" # The path to the folder where blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in frontmatter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "The Nocturnist"}
      - {label: "Tags", name: "tags", widget: "list", default: ["New Post"]}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Image URL", name: "imageUrl", widget: "string", required: false}
      - {label: "Series ID", name: "seriesId", widget: "string", required: false, hint: "Optional: ID of the series this post belongs to (e.g., 'quantum-intro')"}
      - {label: "Series Order", name: "seriesOrder", widget: "number", value_type: "int", required: false, hint: "Optional: Order of this post within the series (e.g., 1, 2, 3)"}
      - {label: "Body", name: "body", widget: "markdown"}
