
backend:
<<<<<<< HEAD
  name: git-gateway # Uses Netlify Identity and Git Gateway
  branch: master # Or your default branch name (e.g., main)
=======
  name: github
  repo: your-github-username/your-repo-name # e.g. owner/repo
  branch: master # Default branch for commits, usually main or master
  auth_type: pkce # Use PKCE flow for better security
  app_id: w6oC2eKlWUktCtJBQVUWtcvOMNjaEQYy # Client ID from your GitHub OAuth App
  # base_url: https://your-custom-domain.com # Optional: if you have a custom domain
  # auth_endpoint: /oauth/authorize # Optional: for custom OAuth server
>>>>>>> f114f83 (Update config.yml)

media_folder: "public/images/blog" # Where to store uploaded images relative to the site root
public_folder: "/images/blog" # The src attribute for "media_folder" in your site

publish_mode: editorial_workflow # Enables a full UI for drafting, reviewing, and publishing

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in frontmatter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "The Nocturnist"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Image URL", name: "imageUrl", widget: "string", required: false}
      - {label: "Image AI Hint", name: "dataAiHint", widget: "string", required: false}
      - {label: "Series ID", name: "seriesId", widget: "string", required: false}
      - {label: "Series Order", name: "seriesOrder", widget: "number", required: false, value_type: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
