
backend:
  name: github
  repo: your-github-username/your-repo-name # IMPORTANT: Replace with your GitHub username/repo (e.g., MyUser/my-nocturnal-codex)
  branch: master # Or 'main', or your default branch name
  auth_type: pkce # Use PKCE flow for better security
  app_id: YOUR_GITHUB_OAUTH_CLIENT_ID # IMPORTANT: Replace with the Client ID from your GitHub OAuth App
  # base_url: https://your-custom-domain.com # Optional: if you have a custom domain
  # auth_endpoint: /oauth/authorize # Optional: for custom auth flows, usually not needed

# This line should be at the root level
publish_mode: editorial_workflow # Recommended for draft/review process

# These lines should be at the root level for media management
media_folder: "public/images/blog" # Path where new media uploads will be stored in the repo
public_folder: "/images/blog" # The public URL path to access media files

collections:
  - name: "blog" # Used in routes, e.g., /admin/#/collections/blog
    label: "Blog Posts" # Display name in the CMS UI
    folder: "content/blog" # Path to the directory in your repo where blog posts are stored
    create: true # Allow creating new posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new posts
    fields: # Defines the fields for each blog post
      - { label: "Title", name: "title", widget: "string", hint: "The main title of the blog post." }
      - { label: "Author", name: "author", widget: "string", default: "The Nocturnist" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ssZ", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Tags", name: "tags", widget: "list", default: ["New Post"], hint: "Keywords related to the post." }
      - { label: "Excerpt", name: "excerpt", widget: "text", hint: "A short summary of the post." }
      - { label: "Cover Image URL", name: "imageUrl", widget: "image", required: false, hint: "Upload or link to an image. Will be stored in 'public/images/blog'." }
      - { label: "Cover Image AI Hint", name: "dataAiHint", widget: "string", required: false, hint: "e.g., 'abstract technology', 'forest path'. For image search if using AI image features."}
      - { label: "Series ID", name: "seriesId", widget: "string", required: false, hint: "e.g., 'quantum-intro'. Used to group posts in a series." }
      - { label: "Series Order", name: "seriesOrder", widget: "number", required: false, value_type: "int", hint: "e.g., 1, 2, 3. Order of this post within its series." }
      - { label: "Body", name: "body", widget: "markdown", hint: "The main content of the post, written in Markdown." }
  # You can add other collections here for different content types, for example:
  # - name: "wiki"
  #   label: "Wiki Articles"
  #   folder: "content/wiki" # Assuming you create a content/wiki folder
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Category", name: "category", widget: "string", required: false }
  #     - { label: "Last Updated", name: "lastUpdated", widget: "datetime" }
  #     - { label: "Body", name: "body", widget: "markdown" }

  # - name: "think_tank"
  #   label: "Think Tank Articles"
  #   folder: "content/think-tank" # Assuming you create a content/think-tank folder
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Authors", name: "authors", widget: "list" }
  #     - { label: "Date", name: "date", widget: "datetime" }
  #     - { label: "Tags", name: "tags", widget: "list", required: false }
  #     - { label: "Abstract", name: "abstract", widget: "text" }
  #     - { label: "Image URL", name: "imageUrl", widget: "image", required: false }
  #     - { label: "Image AI Hint", name: "dataAiHint", widget: "string", required: false }
  #     - { label: "Body", name: "body", widget: "markdown" }

    