
backend:
  name: github
  repo: your-github-username/your-repo-name # IMPORTANT: Replace with your GitHub username/repo
  branch: main # IMPORTANT: Or your default branch (e.g., master)
  auth_type: pkce
  app_id: YOUR_GITHUB_OAUTH_CLIENT_ID # IMPORTANT: Replace with your GitHub OAuth App Client ID
  # base_url: https://your-site.netlify.app # Usually not needed for Netlify + PKCE
  # cms_label_prefix: decap-cms/ # Optional

media_folder: "public/images/blog" # Where Decap CMS saves uploaded images
public_folder: "/images/blog" # The public path to access saved images

publish_mode: editorial_workflow # Enables drafting, reviewing, and publishing posts

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog" # Path to the folder where blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new posts
    fields: # Fields for each blog post
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Author"
        name: "author"
        widget: "string"
        default: "The Nocturnist"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
      - label: "Image URL"
        name: "imageUrl"
        widget: "string"
        required: false
      - label: "Image AI Hint"
        name: "dataAiHint"
        widget: "string"
        required: false
      - label: "Series ID"
        name: "seriesId"
        widget: "string"
        required: false
      - label: "Series Order"
        name: "seriesOrder"
        widget: "number"
        required: false
        value_type: "int"
      - label: "Body"
        name: "body"
        widget: "markdown"
