
# Netlify Identity & Git Gateway
backend:
  name: github
  repo: your-github-username/your-repo-name # e.g. owner/repo
  branch: master # Default branch for commits, usually main or master
  auth_type: pkce # Use PKCE flow for better security
  app_id: YOUR_GITHUB_OAUTH_CLIENT_ID # Client ID from your GitHub OAuth App
  # base_url: https://your-custom-domain.com # Optional: if you have a custom domain
  # auth_endpoint: /oauth/authorize # Optional: for custom OAuth server

# Local backend for development (optional, comment out for production)
# local_backend: true

media_folder: "public/images/blog"
public_folder: "/images/blog"

publish_mode: editorial_workflow # Enables drafting, reviewing, and publishing

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "The Nocturnist"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Image URL", name: "imageUrl", widget: "string", required: false}
      - {label: "Image AI Hint", name: "dataAiHint", widget: "string", required: false}
      - {label: "Series ID", name: "seriesId", widget: "string", required: false}
      - {label: "Series Order", name: "seriesOrder", widget: "number", required: false, value_type: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
