
backend:
  name: github
  repo: your-github-username/your-repo-name # IMPORTANT: Replace with your actual repo path
  branch: main # or your default branch, e.g., master
  auth_type: pkce # Use PKCE flow
  app_id: YOUR_GITHUB_OAUTH_CLIENT_ID # IMPORTANT: Replace with your GitHub OAuth App Client ID
  # site_domain: majestic-longma-cff6c5.netlify.app # Optional: usually auto-detected by Decap

media_folder: "public/images/blog" # Where Decap CMS will store uploaded images
public_folder: "/images/blog" # The public path to access the images in your app

publish_mode: editorial_workflow # Enables drafting, reviewing, and publishing workflow

collections:
  - name: "blog" # Used in routes, e.g., /admin/#/collections/blog
    label: "Blog" # Display name for the collection in the UI
    folder: "content/blog" # The path to the folder where blog posts are stored in your repo
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new posts
    fields: # The fields for each document, usually in frontmatter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "The Nocturnist"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Image URL", name: "imageUrl", widget: "string", required: false}
      - {label: "Image AI Hint", name: "dataAiHint", widget: "string", required: false}
      - {label: "Series ID", name: "seriesId", widget: "string", required: false}
      - {label: "Series Order", name: "seriesOrder", widget: "number", required: false, value_type: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
